service:
  name: spike-ts-serverless-framework

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/*-${self:provider.stage}'
  environment:
    TEST_QUEUE_NAME: ${self:service}-${self:provider.stage}
    IMAGES_DYNAMODB_TABLE: images-${self:service}-${self:provider.stage}
    PIXABAY_API_KEY: ${env:PIXABAY_API_KEY}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-domain-manager

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  customDomain:
    domainName: ${self:provider.stage}-spike-ts-serverless.${env:CUSTOM_DOMAIN_NAME}
    certificateName: ${env:CERTIFICATE_NAME}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'

functions:
  hello:
    handler: src/functions/hello.index
    events:
      - http:
          method: get
          path: hello
  putToSqs:
    handler: src/functions/putToSqs.index
    events:
      - http:
          path: /put-to-sqs
          method: POST
          cors: true
  sqsTriggered:
    handler: src/functions/sqsTriggered.index
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TestQueue
              - Arn
  dynamoTriggered:
    handler: src/functions/dynamoTriggered.index
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - SpikeServerlessFrameworkImagesTable
              - StreamArn

resources:
  Resources:
    TestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.TEST_QUEUE_NAME}
    SpikeServerlessFrameworkImagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.IMAGES_DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: query
            AttributeType: S
        KeySchema:
          - AttributeName: query
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
